language: node_js

node_js:
  - node

script:
  - npm test

addons:
  chrome: stable

before_install: npm install -g grunt-cli

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"